language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
before_install:
  - "npm i -g npm"
  - "sudo apt-get install libicu-dev prosody luarocks"
  - "sudo luarocks install luabitop"
  # Workaround for a permissions issue with Travis virtual machine images
  # that breaks Python's multiprocessing:
  # https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - sudo cp test/resources/prosody.cfg.lua /etc/prosody/prosody.cfg.lua
  - sudo cp test/resources/mod_websocket.lua /usr/lib/prosody/modules/
  - sudo service prosody stop
before_script:
  - npm install -g grunt-cli
script: "npm run integration-test"
after_success:
  - if [ "master" -ne $TRAVIS_BRANCH ]; then exit 0; fi; 
  - git config --global user.email "deploy@travis-ci.org"
  - git config --global user.name "Travis deploy"
  - git remote add github "https://${GH_TOKEN}@github.com/node-xmpp/node-xmpp-client.git" > /dev/null
  - git fetch github
  - git checkout master
  - git add -f node-xmpp-browser.js
  - echo "Added browserified file"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}@github.com" > .git/credentials
  - git commit -a -m "Updating browserified file - build number $TRAVIS_BUILD_NUMBER"
  - git push github master > /dev/null
env:
  global:
  - secure: 'EF0sdrfSkfTIjaQwlFyC+Ma9IOwlKh1N7qKDS0RMo7goq+5cFXOMXvlYguuxPX6YnxBFRWhTz5NNMjeCfjchET0Mu5mvD9aS4g38yAYHsqD0pBxgjXx01rkVo45dtrwASHUWhbupAde7ppbYKbjY5spOvFvyI57Vo/9hcrazyVk='
